language: php
php:
  #- '5.4'
  #- '5.5'
  #- '5.6'
  #- '7.0'
  - '7.1'

before_script:
  # APCu vs APCu
  - if [[ "$(php -v | grep 'PHP 5')" ]]; then yes | pecl install apcu-4.0.8; composer require atoum/atoum:2.9.0; fi
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then yes | pecl install apcu; composer require atoum/atoum; fi
  #- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-add tests/apc.ini
  # No xml report for PHP 5.4
  - if [[ "$(php -v | grep 'PHP 5.4')" ]]; then composer remove atoum/reports-extension; fi
  # composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php -i | grep 'apc'

script: vendor/bin/atoum -c tests/travis.cfg.php

after_success:
    - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: f54a45771b2cdaa50cc762c489a20d4b5e9bdb0f32161874e705585baa02bade

